name: frontend_nhl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.0.0
  injectable: ^2.7.1
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  google_fonts: ^6.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  get_it: ^9.2.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  intl: ^0.20.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/fonts/
